name: Ruby

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.2'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: gem build my_custom_gem.gemspec
    - name: Configure RubyGems credentials
      run: |
        mkdir -p ~/.gem
        echo "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}" > ~/.gem/credentials
      env:
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
    - name: Debug key hash (partial)
      run: echo "${{ secrets.RUBYGEMS_API_KEY }}" | sha256sum
    - name: Set permissions for credentials
      run: chmod 0600 ~/.gem/credentials
    - run: cat ~/.gem/credentials
    - name: Update RubyGems
      run: gem update --system
    - name: Debug RUBYGEMS_API_KEY length
      run: echo "${{ secrets.RUBYGEMS_API_KEY }}" | wc -c
    - run: gem push my_custom_gem-*.gem
